### PR TITLE
Refactor self and magicguis

### PR DESCRIPTION
**Pull request by haesleinhuepf**
Here, I introduced stateful functions. Thus, a magic-factory annotated operation can access a parameter `myself` that is binded after creating the magicgui. 

Todo:
- [ ] widgets still leaking
- [x] After starting a magicgui the second time, operations cannot be chosen anymore

1st start:
image

2nd start:
image

### CODE REVIEW

**Comment by tlambert03** [comment]
we should probably have a zoom conversation at some point.  I don't understand the need for most of this here.  magicgui functions can already access themselves. by using the name of the function (as you used to do).  And the same applies for `magic_factory`.  Would be happy to hear what you were trying to work around with this solution though...

**Comment by haesleinhuepf** [comment]
My major issue was (I think) that magicgui and magicfactory have a static nature. Thus, there was interplay between different dialogs of the same kind attach to different layers (e.g. a chain of denoising operations). With the stateful-functions it works for now. But I would love to have a simplistic approach such as 
```
@magicsomething(...)
def operation(...)...
```
At the moment, crucial code is spread over 3-4 files, and if I had to explain to other image-processing-library folks (e.g. scikit-image or cupy) how to adapt it, I would have a hard time...

I'll take a look at the other PR you sent and then, indeed a zoom meeting makes sense! Thanks for working on this!

**Comment by tlambert03** [comment]
Can you expand on what you mean by “static nature”.  As we discussed the other day `@magicgui` will indeed make a single widget instance.  That instance is not static (ie, it has state and can refer to itself over mutiple calls), but just like any python object, If you make two pointers to it, they will be the same state, such that changing one will affect the other.  `magic_factory` however, creates a class-like object that, when called, produces different widget instances that are not connected to each other.  The other solution for creating multiple disconnected instances, is just to not decorate the function directly, but rather to call `magicgui(my_function)` each time you want to make a new widget instance.  (Which is what I did in that other PR).

**Comment by tlambert03** [comment]
> crucial code is spread over 3-4 files, and if I had to explain to other image-processing-library folks (e.g. scikit-image or cupy) how to adapt it,

In my opinion, you’re biggest problem here is that you’re storing pointers to things on pretty much every object (i.e, you store the LayerDialog both in layer.metadata as well as at “widget.self”, you store the viewer object on the assistant as well as on the magicgui widget, etc...).  This is essentially why things are spread all over the place.  I think the best thing you could do here is to make Assistant be the thing that tracks those relationships, not the things themselves.  (E.g, you would query the assistant object for a dialog corresponding to a layer, rather than just saving it in the widget instance).

In fact, you could probably nearly get rid of the _operations file entirely.  The point of magicgui is to create widgets for functions, so ideally, you should be creating widgets for the functions actually IN pyclesperanto (instead of making new functions that wrap those functions).

**Comment by tlambert03** [comment]
I want to append one more thought to that. 

Since the primary product of this repo is a workflow, I think you would benefit from an object that represents a workflow!  Currently the workflow is buried in the metadata that you attach to each layer, and you must introspect viewer.layers to actually build the workflow when it comes time.  So all the critical info is attached to napari objects, not to your own objects. This comes back to the concept of an “intermediate representation” that we discussed a while ago... that “Pipeline” object would store the inputs outputs, parameters, etc (using layer ids as pointers for instance), and then your export functions would accept pipeline instances, not viewers

**Comment by tlambert03** [comment]
here's a runnable example of what I mean by the pipeline:

```python
from typing import Any, Optional, Sequence, Tuple
from dataclasses import dataclass, field


@dataclass
class Step:
    operation: str
    args: Sequence[Any] = field(default_factory=tuple)  # kwargs might be better
    input: Optional[int] = None
    is_labels: bool = False
    clims: Optional[Tuple[float, float]] = None

    def operate(self, n) -> str:
        args = tuple(map(repr, self.args))
        if self.input:
            args = (f"image{n-1}", f"cle.create_like(image{n-1})") + args
        return f"image{n} = cle.{self.operation}({', '.join(map(str, args))})"

    def show(self, n):
        title = f"Result of {self.operation.replace('_', ' ')}"
        show_args = [f"image{n}", repr(title), str(self.is_labels)]
        if self.clims:
            show_args.extend(map(str, self.clims))
        return f"cle.imshow({', '.join(show_args)})"


@dataclass
class Pipeline:
    steps: Sequence[Step]
    show: bool = True

    def to_jython(self):
        for n, step in enumerate(self.steps):
            yield step.operate(n)
            if self.show:
                yield step.show(n)
            yield ""  # newline


if __name__ == "__main__":
    s0 = Step(operation="imread", args=("Lund_000500",), clims=(125, 680))
    s1 = Step(operation="gaussian_blur", input=s0, args=(1, 1, 0), clims=(0, 657))
    s2 = Step(operation="top_hat_box", input=s1, args=(10, 10, 0), clims=(0, 378))
    s3 = Step(operation="gamma_correction", input=s2, args=(1,), clims=(0, 378))
    s4 = Step(operation="threshold_otsu", input=s3, is_labels=True)
    s5 = Step(
        operation="connected_components_labeling_box",
        input=s3,
        args=(2,),
        is_labels=True,
    )

    pipeline = Pipeline(steps=[s0, s1, s2, s3, s4, s5])

    print("\n".join(pipeline.to_jython()))
```

with that, the main job of `Assistant` just becomes building the `Step` and `Pipeline` objects based on the args from magicgui widget, and the clims from the layer.

**Comment by haesleinhuepf** [comment]
> In fact, you could probably nearly get rid of the _operations file entirely.

Yes, I absolutely believe that this is possible. And then, one could use the assistant to also assemble workflows containing scikit-image and cupy/img operations to complex workflows. They just need to be assignable to categories.

> here's a runnable example of what I mean by the pipeline.

Oh, that looks really good! I love it.

> I think you would benefit from an object that represents a workflow! Currently the workflow is buried in the metadata that you attach to each layer,

I agree. I also have that on ImageJ side. I was attaching the dialogs to the layers in a similar context like [this discussion](https://github.com/napari/napari/pull/2053). You know, a layer has properties such as visibilty and color map. Why shouldn't it have another property `source` which could be a stateful magicgui annotated function. ;-) If napari would have such infrastructure, there would be no need for the whole `LayerDialog` class. I could also see how the code-generators become part or a close friend of magicgui and live independent from clEsperanto and OpenCL. Just saying, I would support every action going in this direction.

**Pull request merged**
