### PR TITLE
Add test2

### PR DESCRIPTION
**Pull request by haesleinhuepf**

### CODE REVIEW

**Comment by tlambert03** [comment]
hmmm... looks like pytest didn't find it.  see this line [in the logs](https://github.com/clEsperanto/napari_pyclesperanto_assistant/pull/8/checks?check_run_id=2300236323#step:10:14):

```
plugins: napari-0.4.7, qt-3.3.0, cov-2.11.1, napari-plugin-engine-0.1.9, benchmark-3.2.3
collecting ... collected 2 items
```

try putting it in a lower step.  (temporarily, even though non-linux doesn't need it)

**Comment by tlambert03** [comment]
> hmmm... looks like pytest didn't find it. 

Oh I know why... it's cause you're _also_ using setup miniconda here :joy: ... so you installed into a different env.

**Comment by haesleinhuepf** [comment]
I'm not sure if I'm crying because I'm laughing or laughing because I'm crying 🤣 
I think the cookiecutter will eventually bring the solution to end such pain. Thanks for your work on this btw. it's really helpful.

**Comment by tlambert03** [comment]
:) yeah... this is a complicated package!

**Comment by tlambert03** [comment]
awesome!  Now, to fix the leaked widgets, see comment [here](https://github.com/napari/napari/issues/2520#issuecomment-816158511).  You can try just putting the `from ._operations` stuff at the top of the module... that would probably do it.  Or try the `magic_factory` stuff in that comment for what is probably the "better" fix.

**Pull request merged**
