### PR TITLE
fix ci

### PR DESCRIPTION
**Pull request by haesleinhuepf**

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
The file ` .github/workflows/test_and_deploy.yml ` is now identical with the one from pyclesperanto. While pyclesperanto's test can find an OpenCL-device, this repository here can't.

I don't get it.

**Comment by tlambert03** [comment]
huh... you might try rerunning on pyclesperanto... it's been a week since the last pass, and things can definitely change in dependencies in that time.  i doubt this would cause pocl to fail, but the last passing test was using pyopencl 2021.2.3 and this one is using 2021.2.5 ...

**Comment by haesleinhuepf** [comment]
Yeah, on pyclesperanto it still works:
https://github.com/clEsperanto/pyclesperanto_prototype/runs/2980262929

**Comment by haesleinhuepf** [comment]
The tests work now on the maste branch :-)

**Comment by tlambert03** [comment]
Awesome, what was it?

**Comment by haesleinhuepf** [comment]
> Awesome, what was it?

I have no idea. I didn't change anything CI related.

**Pull request closed without merging**
